### ISSUE TITLE
Unable to build on Ubuntu 22.04

### ISSUE THREAD

**Issue by ploeffler** [nwdigitalradio/paclink-unix#7]
`wl2ktelnet.c:120:3: error: too many arguments to function ‘g_mime_init’
  120 |   g_mime_init(0);
      |   ^~~~~~~~~~~
In file included from wl2ktelnet.c:69:
/usr/include/gmime-3.0/gmime/gmime.h:125:6: note: declared here
  125 | void g_mime_init (void);
      |      ^~~~~~~~~~~
`
